### PR TITLE
[MCKIN-8520] Engagement score average reflective of Discussion activity by Cohort Group

### PR DESCRIPTION
**Pull request by Agrendalath**
@UmanShahzad, this PR is a part of `[MCKIN-8520]` PR-s.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @Agrendalath! I've created [OSPR-2685](https://openedx.atlassian.net/browse/OSPR-2685) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Review by UmanShahzad — COMMENTED** [review]
:+1: Looks good, but have some comments on the other PR(s), and need to test it after those are addressed.

**Review by UmanShahzad — APPROVED** [review]
:+1:

- [x] I tested this: Followed test instructions on main PR.
- [x] I read through the code
- [x] I checked for accessibility issues
- [x] Includes documentation

**Comment by UmanShahzad** [comment]
@Agrendalath can you update the version in setup.py here to use 1.1.10? I'll then merge and release that tag.

**Pull request merged**
