### PR TITLE
[MCKIN-8511] Fix version

### PR DESCRIPTION
**Pull request by Agrendalath**

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @Agrendalath! I've created [OSPR-2746](https://openedx.atlassian.net/browse/OSPR-2746) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Review by UmanShahzad — APPROVED** [review]

**Review by UmanShahzad — COMMENTED** [review]
Actually we may need to bump to 1.1.12 because we'd have to re-tag too.

**Comment by Agrendalath** [comment]
@UmanShahzad, ah, right. It might have cached the previous one.

**Comment by Agrendalath** [comment]
@UmanShahzad, done!

**Comment by UmanShahzad** [comment]
@Agrendalath It's more that once we try to release on GitHub, one for that version will already exist. I don't know how GitHub handles re-doing a release, but anyway it doesn't hurt to just bump again to prevent any conflicts anywhere.

**Pull request merged**
